x-restart-policy: &restart-policy
  restart: unless-stopped

x-extra-hosts: &extra-hosts
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-rr-app-volumes: &app-volumes
  volumes:
    - ./:/app:rw
    - ./docker/.cli/.bashrc:/root/.bashrc
    - composer:/root/.composer/cache:rw

version: "3.8"
services:
  &h-cli app:
    <<: *restart-policy
    <<: *app-volumes
    <<: *extra-hosts
    image: sd2020/php81-cli-dev-alpine
    hostname: *h-cli
    tty: true
    env_file:
      - .env
    environment:
      DOCKER_TERM: "${TERM:-}"      # pass host $TERM variable
      COLORTERM: "${COLORTERM:-}"   # pass host $COLORTERM variable
    working_dir: /app

volumes:
  composer:
